summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-15.0-arm64/releases/download/2025.03.12/fontconfig-2.15.0-MacOSX-15.0-arm64.release.tar.xz
bin-sha: f605aff399e198dfa463d05219a339a9b8379653243235356360125759ba2d78
