summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-15.0-arm64/releases/download/2025.03.09/fontconfig-2.15.0-MacOSX-15.0-arm64..tar.xz
bin-sha: 37f41541bcc8f22536eee93379f38e2482b3efcbc2bc8c3d842d620b20d6b746
